### Rules ###
rules:
    - pvs1
    - ps1
    - pm1
    - pm2
    - pm4
    - pm5
    - pp3
    - ba1
    - bs1
    - bp3
    - bp4
    - bp7

### Thresholds splicing and pathogenicity prediction tools ###
prediction_tool_threshold:
    pathogenicity_prediction:
        name: "REVEL"
        benign: 0.183
        pathogenic: 0.644
    splicing_prediction:
        name: "SpliceAI"
        benign: 0.1
        pathogenic: 0.2

### Allelee frequency threshold for each gene ###
allele_frequency_threshold:
    threshold_ba1: 0.1
    threshold_bs1: 0.01
    threshold_bs2: 0.01
    threshold_pm2: 0

### Functional thresholds
functional_thresholds:
    threshold_nmd: 1234
    threshold_diff_len_prot_percent: 0.1


### Annotation filesitems
annotation_files:
    root: "/home/katzkean/"
    clinvar:
        root: "clinvar"
        version: "clinvar_july_2023"
        clinvar_snv: "clinvar_20230730_quality_filter_snv.vcf.gz"
        clinvar_small_indel: "clinvar_20230730_quality_filter_small_indel.vcf.gz"
    uniprot:
        root: "variant_classification/genotoscope_data/uniprot/"
        version: "uniprot_feb_2021"
        rep: "UP000005640_9606_repeat_hg19_16columns.bed"

### Variant specific annotations
### Define respective gene specific configuration in the given location
gene_specific_configs:
    root: "/home/katzkean/variant_classification/gene_specific/"
    brca1: "acmg_brca1.yaml"
    brca2: "acmg_brca2.yaml"
