### Thresholds splicing and pathogenicity prediction tools ###
prediction_tool_threshold:
    revel_benign: 0.37
    revel_pathogenic: 0.65
    CADD: 20.0
    phylop: 1.6
    SpliceAI: 0.5
    MaxEntScan: 0.3
    Hbond: 2.0

### Rules ###
rules:
    - pvs1
    - ps1
    - pm1
    - pm2
    - pm4
    - pm5
    - pp3
    - ba1
    - bs1
    - bp3
    - bp4
    - bp7

### Allelee frequency threshold for each gene ###
allele_frequency_threshold:
    BRCA1: 0.1
    BRCA2: 0.1
    BARD1: 0.1
    BRIP1: 0.1
    CDH1: 0.1
    CHEK2: 0.1
    ATM: 0.1
    PALB2: 0.1
    PTEN: 0.1
    RAD51C: 0.1
    RAD51D: 0.1
    P53: 0.1
