#!/usr/bin/env python3

from acmg_rules.ba1 import *
from acmg_rules.bs1 import *
from acmg_rules.bs2 import *
from acmg_rules.bs3 import *
from acmg_rules.bs4 import *
from acmg_rules.bp1 import *
from acmg_rules.bp3 import *
from acmg_rules.bp4 import *
from acmg_rules.bp4_mult_strength import *
from acmg_rules.bp5 import *
from acmg_rules.bp7 import *
from acmg_rules.bp7_deep_intronic import *
from acmg_rules.pvs1 import *
from acmg_rules.pvs1_nocrit import *
from acmg_rules.pvs1_atm import *
from acmg_rules.pvs1_brca1 import *
from acmg_rules.pvs1_brca2 import *
from acmg_rules.pvs1_cdh1 import *
from acmg_rules.pvs1_palb2 import *
from acmg_rules.pvs1_pten import *
from acmg_rules.ps1 import *
from acmg_rules.ps1_enigma import *
from acmg_rules.ps1_pten import *
from acmg_rules.ps1_tp53 import *
from acmg_rules.ps3 import *
from acmg_rules.pm1 import *
from acmg_rules.pm2 import *
from acmg_rules.pm4 import *
from acmg_rules.pm5 import *
from acmg_rules.pm5_ptc import *
from acmg_rules.pm5_cdh1 import *
from acmg_rules.pm5_enigma import *
from acmg_rules.pm5_pten import *
from acmg_rules.pm5_tp53 import *
from acmg_rules.pp1 import *
from acmg_rules.pp2 import *
from acmg_rules.pp3 import *
from acmg_rules.pp3_mult_strength import *
from acmg_rules.pp4 import *
